### ISSUE TITLE
NightServ-Theme appears twice in span.item-label

### ISSUE THREAD

**Issue by ThoraxLaneus** [adrian-abit/nightServ#18]
Hello Sir,
since i really like your extension as off right now, i perceive it as my duty to let you know about an issue i am currently having:

The Item Label of your well-designed extension sadly appears twice through:

`<a href="chrome-extension://{extensionCode}/pages/settings/settings.html"><img class="nav-svg-icon" src="chrome-extension://{extensionCode}/assets/ns24.png"><span class="item-label">nightServ Themes</span><span id="{id}">NEU!</span></a>`
![Classified IServ nightServ 2Themes Bug](https://user-images.githubusercontent.com/83810278/117419913-5cc10c80-af1d-11eb-8f62-cd0a0a0bd09e.png)
Sincerely, ThoraxLaneus

**Comment by adrian-abit** [comment]
Hey, 

Thank you for reporting this Issue. Does this happen all the time or is it something that comes and goes?

May I also ask which Browser + Version you are using, since I can't reproduce this bug myself.

Sincerely
Adrian B.

**Comment by ThoraxLaneus** [comment]
Hi,
thanks for your quick reaction here. Yes, I do get this issue every single time. I use Chrome version 85.0.4183.121. 
Greets, Thorax

**Comment by adrian-abit** [comment]
Hello,

Unfortunately I can't reproduce this error. Could you please make sure you haven't installed nightServ twice?
If you haven't, could you please reinstall nightServ.

Please inform me of the results.

Sincerely
Adrian B.

**Comment by ThoraxLaneus** [comment]
Hi,
I did reinstall nightServ, but unfortunately, i still get the exact same error. Maybe my Chrome version is not the newest one? What's the version you're on? Though I did not negate any update-requests.
Greets, Thorax

**Comment by adrian-abit** [comment]
Hey,

I have tried to replicate this Issue with Chrome Version 90.0.4430.93

It seems that you are behind some Chrome Updates. Can you try updating chrome?
You also haven't answered if you maybe installed nightServ twice. This would be the answer to everything.

Please inform me of the results.

Sincerely
Adrian B.

**Comment by ThoraxLaneus** [comment]
Hi, 
no, i did not install nightServ twice. I will upgrade tomorrow and tell you if that solves the problem. I guess that's the reason for it. But it would be sad if your extension wouldn't be downward-compatable.
Greets, Thorax

**Comment by adrian-abit** [comment]
Hi,

My Addon should be downwards-compatible, It's very weird that this is happening to you. And it shouldn't even be possible.

Please inform me if the update fixed the error.

Sincerely,
Adrian B.

**Comment by ThoraxLaneus** [comment]
Hi,
so, i deinstalled Chrome and then reinstalled it. Now it - the extension works properly.
Greets, Thorax

**Comment by adrian-abit** [comment]
Weird.

But I'm happy that your problem has been resolved!

Sincerely
Adrian B.
