### ISSUE TITLE
Iserv Pinkmode

### ISSUE THREAD

**Issue by Mathew444** [adrian-abit/nightServ#5]
Hello Sir,
I was looking at your repo and i really liked what you did! Could you maybe implement a feature in this addon that makes Iserv pink? I and many others would really appreciate that.
Sincerely,
Mathew

**Comment by adrian-abit** [comment]
Hey,

I am working right now on themes for IServ.  You can then change between different themes including a pink one. 
This will take some time because I am at the same time working on the extension for Firefox. I think I may be done in a week or two.

**Comment by Mathew444** [comment]
Thank you very much for the information. You are doing a great job!
